"""Imagen Categoria

Revision ID: 031399cce022
Revises: 08b708e39836
Create Date: 2024-05-13 17:15:01.915091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031399cce022'
down_revision = '08b708e39836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
