"""Created_atu

Revision ID: 08b708e39836
Revises: d7c8fdda4e0b
Create Date: 2024-05-13 13:30:12.170102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08b708e39836'
down_revision = 'd7c8fdda4e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad_vista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('vistas', sa.Integer(), nullable=False),
    sa.Column('fecha_vista', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('preferencia_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('preferencia_usuario', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('actividad_vista')
    # ### end Alembic commands ###
