"""Updated at

Revision ID: 1475a0f8f842
Revises: 031399cce022
Create Date: 2024-05-24 12:49:35.276214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1475a0f8f842'
down_revision = '031399cce022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('actividad_vista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('preferencia_usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('preferencia_usuario', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('actividad_vista', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
