"""Modify ImagenActividad to store image data as bytes

Revision ID: 322bf6c899b7
Revises: 1475a0f8f842
Create Date: 2024-06-06 12:59:18.659595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322bf6c899b7'
down_revision = '1475a0f8f842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=50), nullable=True))
        batch_op.drop_column('image_url')

    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))
        batch_op.add_column(sa.Column('mimetype', sa.String(length=50), nullable=False))
        batch_op.drop_column('url')
        batch_op.drop_column('es_portada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_portada', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('mimetype')
        batch_op.drop_column('data')
        batch_op.drop_column('name')

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_data')
        batch_op.drop_column('image_name')

    # ### end Alembic commands ###
