"""Actividades

Revision ID: 41f5dba7e4f2
Revises: 265c7dbc6f3b
Create Date: 2024-03-26 19:42:07.131141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f5dba7e4f2'
down_revision = '265c7dbc6f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_superficie')
    op.drop_table('imagen_actividad')
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipos_superficie', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('imagenes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('imageneportada', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.drop_column('imageneportada')
        batch_op.drop_column('imagenes')
        batch_op.drop_column('tipos_superficie')

    op.create_table('imagen_actividad',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actividad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], name='imagen_actividad_actividad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='imagen_actividad_pkey')
    )
    op.create_table('tipo_superficie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actividad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], name='tipo_superficie_actividad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tipo_superficie_pkey')
    )
    # ### end Alembic commands ###
