"""Preferencias

Revision ID: 8e526cbab2fd
Revises: a0c4cb895e94
Create Date: 2024-03-14 11:00:23.227622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e526cbab2fd'
down_revision = 'a0c4cb895e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividad_turistica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('nivel_dificultad', sa.String(length=50), nullable=False),
    sa.Column('nivel_fisico_requerido', sa.String(length=50), nullable=False),
    sa.Column('tiempo_promedio_duracion', sa.String(length=100), nullable=False),
    sa.Column('epoca_recomendada', sa.String(length=100), nullable=False),
    sa.Column('temperatura_minima', sa.Integer(), nullable=True),
    sa.Column('temperatura_maxima', sa.Integer(), nullable=True),
    sa.Column('precipitacion_media_anual', sa.Integer(), nullable=True),
    sa.Column('precio_referencial', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('cotas_maxima', sa.Integer(), nullable=True),
    sa.Column('cotas_minima', sa.Integer(), nullable=True),
    sa.Column('lugar_partida', sa.String(length=100), nullable=False),
    sa.Column('lugar_llegada', sa.String(length=100), nullable=False),
    sa.Column('acceso', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_superficie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_superficie')
    op.drop_table('localizacion')
    op.drop_table('equipamiento')
    op.drop_table('actividad_turistica')
    # ### end Alembic commands ###
