"""Actividades

Revision ID: 9a378e228e07
Revises: dade8c9c357b
Create Date: 2024-04-14 11:35:00.284874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a378e228e07'
down_revision = 'dade8c9c357b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equipamiento')
    op.drop_table('tipo_superficie')
    op.drop_table('localizacion')
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion_equipamiento', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('recomendacion', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('sitio', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cota_maxima', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cota_minima', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('desnivel_subida', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('desnivel_bajada', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lugar_partida', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lugar_llegada', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('tipo_superficie', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('requerimiento_guia', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('localizacion_geografica', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('acceso', sa.Text(), nullable=False))
        batch_op.drop_column('descripcion')

    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_portada', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagen_actividad', schema=None) as batch_op:
        batch_op.drop_column('es_portada')

    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('acceso')
        batch_op.drop_column('localizacion_geografica')
        batch_op.drop_column('requerimiento_guia')
        batch_op.drop_column('tipo_superficie')
        batch_op.drop_column('lugar_llegada')
        batch_op.drop_column('lugar_partida')
        batch_op.drop_column('desnivel_bajada')
        batch_op.drop_column('desnivel_subida')
        batch_op.drop_column('cota_minima')
        batch_op.drop_column('cota_maxima')
        batch_op.drop_column('sitio')
        batch_op.drop_column('recomendacion')
        batch_op.drop_column('descripcion_equipamiento')

    op.create_table('localizacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actividad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('latitud', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitud', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cotas_maxima', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cotas_minima', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lugar_partida', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lugar_llegada', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('acceso', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], name='localizacion_actividad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='localizacion_pkey')
    )
    op.create_table('tipo_superficie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actividad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], name='tipo_superficie_actividad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tipo_superficie_pkey')
    )
    op.create_table('equipamiento',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actividad_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], name='equipamiento_actividad_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='equipamiento_pkey')
    )
    # ### end Alembic commands ###
