"""Modulo recomendador

Revision ID: d49bac861c98
Revises: 322bf6c899b7
Create Date: 2024-06-10 21:05:56.913051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd49bac861c98'
down_revision = '322bf6c899b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('respuestas_formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pregunta1', sa.String(length=50), nullable=False),
    sa.Column('pregunta2', sa.String(length=50), nullable=False),
    sa.Column('pregunta3', sa.String(length=50), nullable=False),
    sa.Column('pregunta4', sa.String(length=50), nullable=False),
    sa.Column('pregunta5', sa.String(length=50), nullable=False),
    sa.Column('pregunta6', sa.String(length=50), nullable=False),
    sa.Column('pregunta7', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('preferencia_usuario')
    op.drop_table('simple_binary_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_binary_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='simple_binary_test_pkey')
    )
    op.create_table('preferencia_usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nivel_dificultad', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tipo_superficie', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('temperatura_minima', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('temperatura_maxima', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='preferencia_usuario_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='preferencia_usuario_pkey')
    )
    op.drop_table('respuestas_formulario')
    # ### end Alembic commands ###
