"""Categoria

Revision ID: d7c8fdda4e0b
Revises: a4c0cc4e7c72
Create Date: 2024-04-21 21:49:42.154059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c8fdda4e0b'
down_revision = 'a4c0cc4e7c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.drop_column('recomendacion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recomendacion', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
