"""Actividades

Revision ID: dade8c9c357b
Revises: 41f5dba7e4f2
Create Date: 2024-03-26 19:54:59.565328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dade8c9c357b'
down_revision = '41f5dba7e4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagen_actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_superficie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividad_turistica.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.drop_column('imageneportada')
        batch_op.drop_column('imagenes')
        batch_op.drop_column('tipos_superficie')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actividad_turistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipos_superficie', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('imagenes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('imageneportada', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('tipo_superficie')
    op.drop_table('imagen_actividad')
    # ### end Alembic commands ###
