"""Preferencias

Revision ID: fb295be28849
Revises: 8e526cbab2fd
Create Date: 2024-03-14 11:04:44.273526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb295be28849'
down_revision = '8e526cbab2fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencia_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nivel_dificultad', sa.String(length=50), nullable=False),
    sa.Column('tipo_superficie', sa.String(length=50), nullable=False),
    sa.Column('temperatura_minima', sa.Integer(), nullable=False),
    sa.Column('temperatura_maxima', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferencia_usuario')
    # ### end Alembic commands ###
